server:
  port: 10086
spring:
  application:
    name: eureka-register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
    eviction-interval-timer-in-ms: 1000 # 扫描失效服务的间隔时间（缺省为60*1000ms）


